package app.quietreader;
import org.junit.Test;
import static org.junit.Assert.*;
import static app.quietreader.Models.*;
import java.util.*;
public class UpdateTest {
    private Document question(){return SourceParser.article(Source.ZHIHU,"<h1>测试问题</h1><div class='QuestionRichText'>问题说明</div><div class='AnswerItem' data-zop='{&quot;itemId&quot;:1}'><div class='AuthorInfo-name'>甲</div><div class='RichContent-inner'><div class='RichText'><p>甲的回答正文</p></div></div></div><div class='AnswerItem' data-zop='{&quot;itemId&quot;:2}'><div class='AuthorInfo-name'>乙</div><div class='RichContent-inner'><div class='RichText'><p>乙的回答正文</p></div></div></div>","https://www.zhihu.com/question/123");}
    @Test public void answersAreIndependentAndQuestionIsNotAnswer(){Document d=question();assertEquals(3,d.sections.size());assertEquals(2,AnswerStream.answers(d));assertEquals("回答 · 甲",d.sections.get(1).label);assertEquals("1",d.sections.get(1).id);}
    @Test public void everyPlatformGetsFoldingWithoutExecutingSource(){for(Source s:Source.values()){Document d=new Document();d.title="<script>bad()</script>";d.url=s.login;d.blocks.add(new Block("text","很长的正文".repeat(300)));String h=ReaderHtml.render(d,s,19);assertTrue(s.name(),h.contains("展开阅读"));assertFalse(h.contains("<script>"));assertTrue(org.jsoup.Jsoup.parse(h).select("section p:not(.preview)").isEmpty());}}
    @Test public void expansionIsPerSectionAndDarkModeDoesNotInvertImages(){Document d=question();String h=ReaderHtml.render(d,Source.ZHIHU,19,true,Set.of("1"),false);assertTrue(h.contains("--bg:#1f2025"));org.jsoup.nodes.Document page=org.jsoup.Jsoup.parse(h);assertEquals("甲的回答正文",page.select("#part-1 > p:not(.preview)").text());assertTrue(page.select("#part-2 > p:not(.preview)").isEmpty());assertTrue(h.contains("加载下一批回答"));assertFalse(h.contains("filter:invert"));}
    @Test public void streamMergeDeduplicatesAndRetainsOldAnswers(){Document a=question(),b=question();Section s=new Section("3","回答 · 丙",true);s.blocks.add(new Block("text","第三个回答"));b.sections.add(s);AnswerStream.merge(a,b);assertEquals(4,a.sections.size());assertEquals(3,AnswerStream.answers(a));AnswerStream.merge(a,b);assertEquals(4,a.sections.size());assertEquals("甲的回答正文",a.sections.get(1).blocks.get(0).value);}
    @Test public void loginPolicySeparatesAuthFromArticleAndRejectsLookalikes(){assertTrue(UrlPolicy.loginAllowed(Source.WEIBO,"https://login.sina.com.cn/sso/login.php"));assertFalse(UrlPolicy.belongs(Source.WEIBO,"https://login.sina.com.cn/sso/login.php"));assertFalse(UrlPolicy.loginAllowed(Source.WEIBO,"https://login.sina.com.cn.evil.test/"));assertFalse(UrlPolicy.loginAllowed(Source.ZHIHU,"https://login.sina.com.cn/"));assertFalse(UrlPolicy.loginAllowed(Source.WEIBO,"intent://login"));}
    @Test public void newBoardsStayOnTheirPlatform()throws Exception{assertEquals(1,SourceParser.list(Source.WALLSTREET,"{\"data\":{\"day_items\":[{\"title\":\"财经新闻\",\"uri\":\"https://wallstreetcn.com/articles/123\"}]}}").size());assertEquals("https://news.ycombinator.com/item?id=42",SourceParser.list(Source.HACKERNEWS,"<table><tr class='athing' id='42'><td><span class='titleline'><a href='https://external.test'>A news story</a></span></td></tr></table>").get(0).url);assertFalse(Source.TOUTIAO.visible());}
    @Test public void smzdmAdsAreNotListEntries()throws Exception{assertEquals(1,SourceParser.list(Source.SMZDM,"<title>精选_3小时内最热优惠排行_什么值得买</title><ul id='feed-main-list'><li data-tab='3h最热' data-type='普通'><h5 class='feed-ver-title'><a href='https://www.smzdm.com/p/123/'>一个正常的热门商品</a></h5></li></ul><aside><a href='https://www.smzdm.com/p/456/'>另一个推广商品推荐</a></aside>").size());}
}
